apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_8e8cd7b71051
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
