apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_3bd5684acc5b
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
