apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: frontend-container
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_c5f1968dfd6e
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
