apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  labels:
    app.kubernetes.io/managed-by: kargocd
  name: krampoline
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: frontend-service # 프론트엔드 서비스의 이름
              servicePort: 5173 # 프론트엔드 서비스의 포트
            path: /
            pathType: Prefix
